#!/usr/bin/env python3
import pytest

from cry.classical.substitution import Substitution

def test_frequency():
    s = Substitution()
    s.random_key()
    m = 'northgkoreasintroductionofthepukguksongsubmarinelaunchedballisticmissileisagravemomentfornortheastasianregionalsecurityandareminderofwhathasbeenlostovernearlytwoyearsofallshownosubstancediplomacythismissileisdestinedforasubmarinebutitwasntlaunchedfromonenorthkoreasengineersmayhavedeemedittooriskytostaketheironeoperationalballisticmissilesubmarineinatestneverthelessthemissileappearstohavesuccessfullycompleteditsflightwithflyingcoloursthepukguksongifithadbeenflownatamorenormalanglecouldhavereachedallofjapansfourmainislandsandallofsouthkoreafromthecentreoftheseaofjapanmostseriouslyitrepresentsthelargesteversolidfuelsystemseeninnorthkoreasolidfuelmissileshavemanyadvantagesovertheirliquidfuelcounterpartstheyoffergreaterresponsivenessandflexibilityunliketheirliquidcounterpartstheydonotrequireextensivefuellingandpreparationbeforeusethistestunderscoreswhytheunitedstatesmustmakeextensiveeffortstofreezenorthkoreasqualitativeprogressonmissiletechnologiesankitpandaisadjunctseniorfellowatthefederationofamericanscientistsandauthorofforthcomingbookkimjongunandthebomb'
    c = s.encrypt(m)
    s.frequency(c)
    m_ = s.decrypt(c)
    assert(m == m_)
